// Quick test of the running server

const http = require('http');

function testEndpoint(path, method = 'GET', data = null) {
  return new Promise((resolve, reject) => {
    const options = {
      hostname: 'localhost',
      port: 5000,
      path: path,
      method: method,
      headers: {
        'Content-Type': 'application/json',
      }
    };

    const req = http.request(options, (res) => {
      let data = '';
      res.on('data', (chunk) => {
        data += chunk;
      });
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          resolve({ status: res.statusCode, data: parsed });
        } catch (e) {
          resolve({ status: res.statusCode, data: data });
        }
      });
    });

    req.on('error', (err) => {
      reject(err);
    });

    if (data) {
      req.write(JSON.stringify(data));
    }
    req.end();
  });
}

async function runTests() {
  console.log('🧪 Testing server endpoints...\n');

  try {
    // Test analytics endpoint
    console.log('📊 Testing Analytics Endpoint...');
    const analyticsResult = await testEndpoint('/api/analytics/market/dynamic?skill=Mobile Development&location=India');
    
    if (analyticsResult.status === 200 && analyticsResult.data.success) {
      console.log('✅ Analytics endpoint working!');
      console.log('   Generated by:', analyticsResult.data.generatedBy);
      console.log('   Skill:', analyticsResult.data.data.skill);
      console.log('   Salary:', analyticsResult.data.data.marketOverview?.averageSalary);
      console.log('   Growth:', analyticsResult.data.data.marketOverview?.growthRate);
      console.log('   Job Openings:', analyticsResult.data.data.marketOverview?.jobOpenings);
    } else {
      console.log('❌ Analytics endpoint failed:', analyticsResult.status);
      console.log('   Response:', analyticsResult.data);
    }

    console.log('\n🗺️ Testing Roadmap Endpoint...');
    const roadmapResult = await testEndpoint('/api/roadmaps/generate/dynamic', 'POST', {
      skill: 'Mobile Development',
      level: 'intermediate',
      duration: '3-6 months'
    });
    
    if (roadmapResult.status === 200 && roadmapResult.data.success) {
      console.log('✅ Roadmap endpoint working!');
      console.log('   Generated by:', roadmapResult.data.generatedBy);
      console.log('   Title:', roadmapResult.data.data.title);
      console.log('   Chapters:', roadmapResult.data.data.chapters?.length);
      console.log('   First chapter:', roadmapResult.data.data.chapters?.[0]?.title);
    } else {
      console.log('❌ Roadmap endpoint failed:', roadmapResult.status);
      console.log('   Response:', roadmapResult.data);
    }

    console.log('\n🎯 SUMMARY:');
    console.log('Backend server is running and responding to API calls!');
    console.log('Frontend should now be able to connect and get real data.');

  } catch (error) {
    console.error('❌ Test failed:', error.message);
  }
}

runTests();
