// Quick test to see the debugging output

async function testDebug() {
  console.log('🧪 TESTING WITH DEBUG OUTPUT');
  console.log('='*40);
  
  const skills = ['Mobile Development', 'Data Science', 'Python'];
  
  for (const skill of skills) {
    console.log(`\n🔍 Testing: ${skill}`);
    console.log('-'*30);
    
    try {
      const response = await fetch('http://localhost:5000/api/roadmaps/generate/dynamic', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          skill: skill,
          level: 'beginner',
          duration: '3-6 months'
        })
      });
      
      const data = await response.json();
      
      if (data.success) {
        console.log(`✅ Response for ${skill}:`);
        console.log(`   Title: "${data.data.title}"`);
        console.log(`   First Chapter: "${data.data.chapters?.[0]?.title}"`);
        console.log(`   Generated by: ${data.generatedBy}`);
        
        // Check if it matches the skill
        const titleMatches = data.data.title.includes(skill);
        const chapterMatches = data.data.chapters?.[0]?.title.toLowerCase().includes(skill.toLowerCase());
        
        if (!titleMatches && !chapterMatches) {
          console.log(`❌ MISMATCH: Expected content for "${skill}" but got different content!`);
        }
      } else {
        console.log(`❌ Failed for ${skill}`);
      }
    } catch (error) {
      console.log(`❌ Error for ${skill}:`, error.message);
    }
  }
}

testDebug().catch(console.error);
