import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { 
  Target, 
  Loader, 
  ChevronDown, 
  ChevronRight,
  Play,
  CheckCircle,
  Lock,
  Video,
  BookOpen,
  Award,
  Clock,
  ExternalLink,
  Sparkles,
  TrendingUp
} from 'lucide-react';
import roadmapService from '../services/roadmapService';
import youtubeService from '../services/youtubeService';

const DynamicRoadmap = () => {
  const [selectedSkill, setSelectedSkill] = useState('');
  const [selectedLevel, setSelectedLevel] = useState('beginner');
  const [roadmap, setRoadmap] = useState(null);
  const [loading, setLoading] = useState(false);
  const [expandedChapter, setExpandedChapter] = useState(null);
  const [youtubeVideos, setYoutubeVideos] = useState({});
  const [loadingVideos, setLoadingVideos] = useState({});

  const popularSkills = [
    'Mobile Development', 'Data Science', 'Python', 'JavaScript', 'React', 
    'Node.js', 'Machine Learning', 'Web Development', 'iOS Development',
    'Android Development', 'Flutter', 'Swift', 'Kotlin', 'DevOps',
    'Cloud Computing', 'Cybersecurity', 'Blockchain', 'AI/ML',
    'Java', 'C++', 'Go', 'Rust', 'TypeScript', 'Angular', 'Vue.js'
  ];

  const generateRoadmap = async () => {
    if (!selectedSkill) {
      alert('Please enter or select a skill');
      return;
    }

    setLoading(true);
    console.log(`🚀 Frontend: Generating roadmap for "${selectedSkill}" at ${selectedLevel} level`);
    
    try {
      const result = await roadmapService.generateDynamicRoadmap(
        selectedSkill,
        selectedLevel,
        '3-6 months'
      );
      
      console.log('Frontend: Received roadmap response:', result);
      
      if (result.success && result.data) {
        console.log(`✅ Frontend: Roadmap generated - Title: "${result.data.title}"`);
        console.log(`   Chapters: ${result.data.chapters?.length || 0}`);
        console.log(`   Generated by: ${result.generatedBy || 'Unknown'}`);
        
        setRoadmap(result.data);
        setExpandedChapter(null);
        setYoutubeVideos({});
      } else {
        console.error('❌ Frontend: Roadmap generation failed', result);
        alert(`Failed to generate roadmap for ${selectedSkill}. Please try again.`);
      }
    } catch (error) {
      console.error('❌ Frontend Error generating roadmap:', error);
      alert(`Error generating roadmap for ${selectedSkill}: ${error.message}`);
    } finally {
      setLoading(false);
    }
  };

  const fetchYoutubeVideos = async (chapterIndex, chapter) => {
    if (youtubeVideos[chapterIndex] || loadingVideos[chapterIndex]) {
      return;
    }

    setLoadingVideos(prev => ({ ...prev, [chapterIndex]: true }));

    try {
      const searchQuery = `${chapter.title} ${roadmap.title} tutorial`;
      const result = await youtubeService.searchVideos(searchQuery, {
        maxResults: 3,
        safeSearch: 'strict'
      });

      if (result.success && result.data.videos) {
        setYoutubeVideos(prev => ({
          ...prev,
          [chapterIndex]: result.data.videos
        }));
      }
    } catch (error) {
      console.error('Error fetching YouTube videos:', error);
    } finally {
      setLoadingVideos(prev => ({ ...prev, [chapterIndex]: false }));
    }
  };

  const toggleChapter = (index) => {
    if (expandedChapter === index) {
      setExpandedChapter(null);
    } else {
      setExpandedChapter(index);
      if (roadmap?.chapters?.[index]) {
        fetchYoutubeVideos(index, roadmap.chapters[index]);
      }
    }
  };

  const getDifficultyColor = (difficulty) => {
    const level = difficulty?.toLowerCase() || 'beginner';
    if (level.includes('begin') || level.includes('easy')) {
      return 'bg-green-100 text-green-700';
    } else if (level.includes('inter') || level.includes('medium')) {
      return 'bg-yellow-100 text-yellow-700';
    } else if (level.includes('adv') || level.includes('hard')) {
      return 'bg-red-100 text-red-700';
    }
    return 'bg-gray-100 text-gray-700';
  };

  return (
    <div className="max-w-7xl mx-auto p-6">
      {/* Skill Selection */}
      <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
        <h2 className="text-2xl font-bold text-gray-800 mb-6 flex items-center gap-3">
          <Sparkles className="w-8 h-8 text-purple-500" />
          Generate AI-Powered Learning Roadmap
        </h2>

        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Enter a skill or select from popular choices
            </label>
            <input
              type="text"
              value={selectedSkill}
              onChange={(e) => setSelectedSkill(e.target.value)}
              placeholder="e.g., Python, React, Machine Learning..."
              className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
            />
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Popular Skills
            </label>
            <div className="flex flex-wrap gap-2">
              {popularSkills.map((skill) => (
                <button
                  key={skill}
                  onClick={() => setSelectedSkill(skill)}
                  className={`px-3 py-1 rounded-full text-sm font-medium transition-all ${
                    selectedSkill === skill
                      ? 'bg-blue-500 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {skill}
                </button>
              ))}
            </div>
          </div>

          <div>
            <label className="block text-sm font-medium text-gray-700 mb-2">
              Skill Level
            </label>
            <div className="flex gap-4">
              {['beginner', 'intermediate', 'advanced'].map((level) => (
                <button
                  key={level}
                  onClick={() => setSelectedLevel(level)}
                  className={`px-4 py-2 rounded-lg font-medium capitalize transition-all ${
                    selectedLevel === level
                      ? 'bg-blue-500 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {level}
                </button>
              ))}
            </div>
          </div>

          <button
            onClick={generateRoadmap}
            disabled={loading || !selectedSkill}
            className="w-full py-3 bg-gradient-to-r from-blue-500 to-purple-600 text-white font-semibold rounded-lg hover:from-blue-600 hover:to-purple-700 transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
          >
            {loading ? (
              <>
                <Loader className="w-5 h-5 animate-spin" />
                Generating AI Roadmap...
              </>
            ) : (
              <>
                <Target className="w-5 h-5" />
                Generate Personalized Roadmap
              </>
            )}
          </button>
        </div>
      </div>

      {/* Generated Roadmap */}
      {roadmap && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
        >
          {/* Roadmap Header */}
          <div className="bg-white rounded-xl shadow-lg p-6 mb-6">
            <h3 className="text-2xl font-bold text-gray-800 mb-2">
              {roadmap.title}
            </h3>
            <p className="text-gray-600 mb-4">{roadmap.description}</p>
            
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="p-4 bg-blue-50 rounded-lg">
                <Clock className="w-6 h-6 text-blue-500 mb-2" />
                <p className="text-sm text-gray-600">Duration</p>
                <p className="font-semibold text-gray-800">{roadmap.totalDuration}</p>
              </div>
              <div className="p-4 bg-green-50 rounded-lg">
                <TrendingUp className="w-6 h-6 text-green-500 mb-2" />
                <p className="text-sm text-gray-600">Difficulty</p>
                <p className="font-semibold text-gray-800 capitalize">{roadmap.difficulty}</p>
              </div>
              <div className="p-4 bg-purple-50 rounded-lg">
                <BookOpen className="w-6 h-6 text-purple-500 mb-2" />
                <p className="text-sm text-gray-600">Chapters</p>
                <p className="font-semibold text-gray-800">{roadmap.chapters?.length || 0}</p>
              </div>
              <div className="p-4 bg-yellow-50 rounded-lg">
                <Award className="w-6 h-6 text-yellow-500 mb-2" />
                <p className="text-sm text-gray-600">Salary Range</p>
                <p className="font-semibold text-gray-800">{roadmap.estimatedSalaryRange || 'N/A'}</p>
              </div>
            </div>

            {roadmap.prerequisites && roadmap.prerequisites.length > 0 && (
              <div className="mt-4 p-4 bg-gray-50 rounded-lg">
                <p className="font-medium text-gray-700 mb-2">Prerequisites:</p>
                <div className="flex flex-wrap gap-2">
                  {roadmap.prerequisites.map((prereq, index) => (
                    <span key={index} className="px-3 py-1 bg-white rounded-full text-sm text-gray-600">
                      {prereq}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* Chapters */}
          <div className="space-y-4">
            {roadmap.chapters?.map((chapter, index) => (
              <motion.div
                key={chapter.id || index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ duration: 0.4, delay: index * 0.1 }}
                className="bg-white rounded-xl shadow-lg overflow-hidden"
              >
                <div
                  className="p-6 cursor-pointer hover:bg-gray-50 transition-colors"
                  onClick={() => toggleChapter(index)}
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-4">
                      <div className="w-10 h-10 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full flex items-center justify-center text-white font-bold">
                        {index + 1}
                      </div>
                      <div>
                        <h4 className="text-lg font-semibold text-gray-800">
                          {chapter.title}
                        </h4>
                        <p className="text-gray-600">{chapter.description}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-4">
                      <span className={`px-3 py-1 rounded-full text-sm font-medium ${getDifficultyColor(chapter.difficulty)}`}>
                        {chapter.difficulty}
                      </span>
                      <span className="text-sm text-gray-600">{chapter.duration}</span>
                      {expandedChapter === index ? (
                        <ChevronDown className="w-5 h-5 text-gray-400" />
                      ) : (
                        <ChevronRight className="w-5 h-5 text-gray-400" />
                      )}
                    </div>
                  </div>
                </div>

                {expandedChapter === index && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: 'auto', opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3 }}
                    className="border-t border-gray-200"
                  >
                    <div className="p-6 bg-gray-50">
                      <div className="grid md:grid-cols-2 gap-6">
                        {/* Topics */}
                        {chapter.topics && chapter.topics.length > 0 && (
                          <div>
                            <h5 className="font-semibold text-gray-800 mb-3">Topics Covered</h5>
                            <ul className="space-y-2">
                              {chapter.topics.map((topic, topicIndex) => (
                                <li key={topicIndex} className="flex items-start gap-2">
                                  <CheckCircle className="w-4 h-4 text-green-500 mt-0.5" />
                                  <span className="text-gray-700">{topic}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}

                        {/* Learning Objectives */}
                        {chapter.learningObjectives && chapter.learningObjectives.length > 0 && (
                          <div>
                            <h5 className="font-semibold text-gray-800 mb-3">Learning Objectives</h5>
                            <ul className="space-y-2">
                              {chapter.learningObjectives.map((objective, objIndex) => (
                                <li key={objIndex} className="flex items-start gap-2">
                                  <Target className="w-4 h-4 text-blue-500 mt-0.5" />
                                  <span className="text-gray-700">{objective}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}

                        {/* Projects */}
                        {chapter.practicalProjects && chapter.practicalProjects.length > 0 && (
                          <div>
                            <h5 className="font-semibold text-gray-800 mb-3">Practical Projects</h5>
                            <ul className="space-y-2">
                              {chapter.practicalProjects.map((project, projIndex) => (
                                <li key={projIndex} className="flex items-start gap-2">
                                  <Award className="w-4 h-4 text-purple-500 mt-0.5" />
                                  <span className="text-gray-700">{project}</span>
                                </li>
                              ))}
                            </ul>
                          </div>
                        )}

                        {/* YouTube Videos */}
                        <div className="md:col-span-2">
                          <h5 className="font-semibold text-gray-800 mb-3">Recommended YouTube Videos</h5>
                          
                          {loadingVideos[index] ? (
                            <div className="flex items-center justify-center p-4 bg-white rounded-lg">
                              <Loader className="w-5 h-5 animate-spin text-blue-500 mr-2" />
                              <span className="text-gray-600">Loading videos...</span>
                            </div>
                          ) : (
                            <div className="space-y-3">
                              {chapter.youtubeVideos && chapter.youtubeVideos.length > 0 ? (
                                chapter.youtubeVideos.map((video, videoIndex) => (
                                  <div
                                    key={videoIndex}
                                    className="flex items-center gap-3 p-3 bg-white rounded-lg hover:shadow-md transition-shadow cursor-pointer"
                                    onClick={() => youtubeService.openVideo(video.id)}
                                  >
                                    <div className="relative">
                                      <img
                                        src={youtubeService.getThumbnailUrl(video.thumbnail, 'medium')}
                                        alt={video.title}
                                        className="w-20 h-15 object-cover rounded"
                                        onError={(e) => {
                                          e.target.src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA4MCA2MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjgwIiBoZWlnaHQ9IjYwIiBmaWxsPSIjRjNGNEY2Ii8+CjxwYXRoIGQ9Ik0zMiA0MEwzMiAyMEw0OCAzMEwzMiA0MFoiIGZpbGw9IiM2QjczODAiLz4KPC9zdmc+';
                                        }}
                                      />
                                      <Play className="absolute inset-0 m-auto w-6 h-6 text-white drop-shadow-lg" />
                                    </div>
                                    <div className="flex-1">
                                      <p className="font-medium text-gray-800 line-clamp-1">{video.title}</p>
                                      <div className="flex items-center gap-2 text-sm text-gray-600">
                                        <Video className="w-3 h-3" />
                                        <span>{video.channel?.title}</span>
                                        {video.duration && <span>• {youtubeService.formatDuration(video.duration)}</span>}
                                      </div>
                                    </div>
                                    <ExternalLink className="w-4 h-4 text-gray-400" />
                                  </div>
                                ))
                              ) : youtubeVideos[index] && youtubeVideos[index].length > 0 ? (
                                youtubeVideos[index].map((video, videoIndex) => (
                                  <div
                                    key={videoIndex}
                                    className="flex items-center gap-3 p-3 bg-white rounded-lg hover:shadow-md transition-shadow cursor-pointer"
                                    onClick={() => youtubeService.openVideo(video.id)}
                                  >
                                    <div className="relative">
                                      <img
                                        src={youtubeService.getThumbnailUrl(video.thumbnail, 'medium')}
                                        alt={video.title}
                                        className="w-20 h-15 object-cover rounded"
                                        onError={(e) => {
                                          e.target.src = 'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODAiIGhlaWdodD0iNjAiIHZpZXdCb3g9IjAgMCA4MCA2MCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjgwIiBoZWlnaHQ9IjYwIiBmaWxsPSIjRjNGNEY2Ii8+CjxwYXRoIGQ9Ik0zMiA0MEwzMiAyMEw0OCAzMEwzMiA0MFoiIGZpbGw9IiM2QjczODAiLz4KPC9zdmc+';
                                        }}
                                      />
                                      <Play className="absolute inset-0 m-auto w-6 h-6 text-white drop-shadow-lg" />
                                    </div>
                                    <div className="flex-1">
                                      <p className="font-medium text-gray-800 line-clamp-1">{video.title}</p>
                                      <div className="flex items-center gap-2 text-sm text-gray-600">
                                        <Video className="w-3 h-3" />
                                        <span>{video.channel?.title}</span>
                                        {video.duration && <span>• {youtubeService.formatDuration(video.duration)}</span>}
                                      </div>
                                    </div>
                                    <ExternalLink className="w-4 h-4 text-gray-400" />
                                  </div>
                                ))
                              ) : (
                                <p className="text-gray-500 text-center py-4">No videos available</p>
                              )}
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  </motion.div>
                )}
              </motion.div>
            ))}
          </div>

          {/* Career Outcomes */}
          {roadmap.careerOutcomes && roadmap.careerOutcomes.length > 0 && (
            <div className="bg-white rounded-xl shadow-lg p-6 mt-6">
              <h3 className="text-lg font-semibold text-gray-800 mb-4">Career Outcomes</h3>
              <div className="grid md:grid-cols-3 gap-4">
                {roadmap.careerOutcomes.map((outcome, index) => (
                  <div key={index} className="p-4 bg-gradient-to-br from-blue-50 to-purple-50 rounded-lg">
                    <Award className="w-6 h-6 text-purple-500 mb-2" />
                    <p className="font-medium text-gray-800">{outcome}</p>
                  </div>
                ))}
              </div>
            </div>
          )}
        </motion.div>
      )}
    </div>
  );
};

export default DynamicRoadmap;
